[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "SpaceMono"
style = "Bold"

[font.bold_italic]
family = "SpaceMono"
style = "Bold Italic"

[font.italic]
family = "SpaceMono"
style = "Italic"

[font.normal]
family = "SpaceMono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[shell]
# Tmux config
# program = "/usr/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]

# Zellij config
program = "zellij"
# args = ["attach", "--index", "0", "--create"]

[env]
SHELL = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
