theme = "ayu_dark"

[editor]
line-number = "relative"
cursorline = true
true-color = true
bufferline = "multiple"
color-modes = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
right = ["file-name", "diagnostics", "selections", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false  # false shows hidden files, true ignores hidden files

# Keymaps
[keys.normal]
A-n = "extend_search_next"
A-N = "extend_search_prev"
C-r = ":reload-all"
A-k = ["extend_line", "delete_selection", "move_line_up", "paste_before", "collapse_selection"]
A-j = ["extend_line", "delete_selection", "move_line_down", "paste_before", "collapse_selection"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection"]
"$" = ["search_selection", "select_mode"]
"space" = {"space" = "buffer_picker", "n" = ":set lsp.display-inlay-hints true", "m" = ":set lsp.display-inlay-hints false"}
"0" = ["goto_line_start", "move_next_word_start", "collapse_selection"]
"X" = "extend_line_above"
"C-pageup" = ":buffer-previous"
"C-pagedown" = ":buffer-next"
"A-w" = "goto_prev_diag"
"A-e" = "goto_next_diag"
"A-r" = "goto_prev_parameter"
"A-t" = "goto_next_parameter"
"A-y" = "goto_prev_change"
"A-u" = "goto_next_change"


[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
